### ISSUE TITLE
Live Website Not Updating?

### ISSUE THREAD

**Issue by jgy4** [nickeubank/polling_access_project#1]
Hi all,

I added an "Early Voting" post to the content folder, and was able to see the changes reflected on the local mock-up of the website (using hugo server) on my laptop. But after pushing the changes I don't see them reflected in the live version of the website. I might be overlooking something small here - would love to know if anyone's had similar issues or sees the problem!

**Comment by nickeubank** [comment]
Running hugo server creates a live version of the site, but to have it build html files that GitHub pages can host, you have to run 'hugo' (just that, not with server after). Then commit and push.

**Comment by jgy4** [comment]
Thank you - that fixed it!
